[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
description = "The cargo project, kvs, builds a command-line key-value store client called kvs, which in turn calls into a library called kvs."
authors = ["Abhishek Shah <abhishekshah3@gmail.com>"]

[[bin]]
name = "kvs"
path = "src/bin/main.rs"

[lib]
name = "kvs"
path = "src/lib.rs"
doctest = false
test = false

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
thiserror = "1.0.38"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.4.0"
walkdir = "2.3.2"
