name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [ready_for_review, synchronize]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Run with debug logging"
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free up space on runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install protoc
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0
        with:
          cache-on-failure: true
          cache-all-crates: true

      - uses: actions/checkout@v3
      - name: check
        run: cargo check --workspace --verbose

      - name: Run tests
        run: cargo test --verbose
